shelter_1 = Shelter.create!(foster_program: true, name: "Adopt em all!", city: "Denver", rank: 5)
shelter_2 = Shelter.create!(foster_program: true, name: "Dogs Dogs Dogs", city: "Denver", rank: 7)
shelter_3 = Shelter.create!(foster_program: true, name: "Cats Cats Cats", city: "Boulder", rank: 3)
shelter_1.pets.create!(adoptable: true, age: 3, breed: "mutt", name: "Sparky")
shelter_2.pets.create!(adoptable: true, age: 4, breed: "Beagle", name: "Professor Snuggles")
shelter_2.pets.create!(adoptable: true, age: 2, breed: "Lab", name: "Howard")
shelter_3.pets.create!(adoptable: true, age: 8, breed: "cat", name: "Dexter")